require('dotenv').config();

const {
  NODE_ENV = 'development',
  PORT = 3001,
  EMAIL_ADDRESS = 'test@domain.zone',
  EMAIL_PASS = 'password',
  ORIGIN,
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  UPLOAD_FILE_FOLDER,
  UPLOAD_FOLDER_PATH,
} = process.env;

const ACCEPTED_FILE_TYPES = /jpeg|jpg|png|gif/;
const MAX_FILE_FORM_FILES = 1;
const MAX_MULTIPART_FORM_FIELDS = 0;
const MAX_FILE_SIZE = 5E6;
const NEWS_IMAGE_FIELDNAME = 'news-image';
const NEWS_IMAGE_FOLDER = NEWS_IMAGE_FIELDNAME;
const SPECIALIST_IMAGE_FIELDNAME = 'specialist-avatar';
const SPECIALIST_IMAGE_FOLDER = 'specialists';

module.exports = {
  NODE_ENV,
  PORT,
  EMAIL_ADDRESS,
  EMAIL_PASS,
  ORIGIN,
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  UPLOAD_FILE_FOLDER,
  ACCEPTED_FILE_TYPES,
  MAX_FILE_FORM_FILES,
  MAX_MULTIPART_FORM_FIELDS,
  MAX_FILE_SIZE,
  NEWS_IMAGE_FIELDNAME,
  NEWS_IMAGE_FOLDER,
  SPECIALIST_IMAGE_FIELDNAME,
  SPECIALIST_IMAGE_FOLDER,
  UPLOAD_FOLDER_PATH,
};
